CREATE TABLE AIRLINES (IATA_CODE VARCHAR,	AIRLINE VARCHAR);
CREATE TABLE AIRPORTS (IATA_CODE VARCHAR, AIRPORT VARCHAR,CITY VARCHAR,STATE VARCHAR,
                       COUNTRY VARCHAR,LATITUDE DOUBLE PRECISION,LONGITUDE DOUBLE PRECISION);
DROP TABLE FLIGHTS;
CREATE TABLE FLIGHTS (YEAR INT,MONTH INT,DAY INT,DAY_OF_WEEK INT,AIRLINE VARCHAR,
                      FLIGHT_NUMBER INT,TAIL_NUMBER VARCHAR,ORIGIN_AIRPORT	VARCHAR,
					  DESTINATION_AIRPORT VARCHAR,SCHEDULED_DEPARTURE TIME,DEPARTURE_TIME TIME,
					  DEPARTURE_DELAY INT,TAXI_OUT INT,WHEELS_OFF TIME,SCHEDULED_TIME INT,
					  ELAPSED_TIME INT,AIR_TIME INT,DISTANCE INT,WHEELS_ON TIME,TAXI_IN INT,
					  SCHEDULED_ARRIVAL	TIME,ARRIVAL_TIME TIME,ARRIVAL_DELAY INT,DIVERTED INT,
					  CANCELLED	INT,CANCELLATION_REASON	VARCHAR,AIR_SYSTEM_DELAY INT,
					  SECURITY_DELAY INT,AIRLINE_DELAY INT,LATE_AIRCRAFT_DELAY	INT,
					  WEATHER_DELAY INT);

--IMPORT FILES
COPY AIRLINES (IATA_CODE,	AIRLINE)
FROM 'C:\Program Files\PostgreSQL\17\data\DATASETS\airlines.csv'
DELIMITER ',' CSV HEADER ENCODING 'LATIN1';

COPY AIRPORTS (IATA_CODE,AIRPORT,CITY,STATE,COUNTRY,LATITUDE,LONGITUDE)
FROM 'C:\Program Files\PostgreSQL\17\data\DATASETS\airports.csv'
DELIMITER ',' CSV HEADER ENCODING 'LATIN1';

COPY FLIGHTS (YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,
			  DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,DEPARTURE_TIME,DEPARTURE_DELAY,
			  TAXI_OUT,WHEELS_OFF,SCHEDULED_TIME,ELAPSED_TIME,AIR_TIME,DISTANCE,WHEELS_ON,
			  TAXI_IN,SCHEDULED_ARRIVAL,ARRIVAL_TIME,ARRIVAL_DELAY,DIVERTED,CANCELLED,
			  CANCELLATION_REASON,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,
			  LATE_AIRCRAFT_DELAY,WEATHER_DELAY)
FROM 'C:\Program Files\PostgreSQL\17\data\DATASETS\flights.csv'
DELIMITER ',' CSV HEADER ENCODING 'LATIN1';

--INITIAL DATA REVIEW
SELECT COUNT(*) AS ROW_COUNT FROM AIRLINES;
SELECT COUNT(*) AS ROW_COUNT FROM AIRPORTS;
SELECT COUNT(*) AS ROW_COUNT FROM FLIGHTS;

SELECT * FROM AIRLINES;
SELECT * FROM AIRPORTS;
SELECT * FROM FLIGHTS;

--DATA PROCESSING
--Handle missing values
SELECT * FROM FLIGHTS
WHERE CANCELLATION_REASON IS NULL;

UPDATE FLIGHTS 
SET CANCELLATION_REASON= CASE WHEN CANCELLATION_REASON IS NULL THEN 'NA'
                WHEN CANCELLATION_REASON IS NOT NULL THEN CANCELLATION_REASON END;

SELECT * FROM FLIGHTS
WHERE AIRLINE IS NULL OR FLIGHT_NUMBER IS NULL;

SELECT SCHEDULED_DEPARTURE,DEPARTURE_TIME,SCHEDULED_ARRIVAL,ARRIVAL_TIME,CANCELLATION_REASON
FROM FLIGHTS
WHERE SCHEDULED_DEPARTURE IS NULL OR DEPARTURE_TIME IS NULL OR SCHEDULED_ARRIVAL IS NULL OR
      ARRIVAL_TIME IS NULL;


SELECT * FROM FLIGHTS
WHERE AIR_SYSTEM_DELAY IS NULL OR SECURITY_DELAY IS NULL OR AIRLINE_DELAY IS NULL OR
      LATE_AIRCRAFT_DELAY IS NULL OR WEATHER_DELAY IS NULL;

UPDATE FLIGHTS 
SET AIR_SYSTEM_DELAY =0
	WHERE AIR_SYSTEM_DELAY IS NULL;
UPDATE FLIGHTS 
SET SECURITY_DELAY =0
	WHERE SECURITY_DELAY IS NULL;
UPDATE FLIGHTS 
SET AIRLINE_DELAY =0
	WHERE AIRLINE_DELAY IS NULL;
UPDATE FLIGHTS 
SET LATE_AIRCRAFT_DELAY =0
	WHERE LATE_AIRCRAFT_DELAY IS NULL;
UPDATE FLIGHTS 
SET WEATHER_DELAY =0
	WHERE WEATHER_DELAY IS NULL;

SELECT SCHEDULED_DEPARTURE,DEPARTURE_TIME,DEPARTURE_DELAY,SCHEDULED_ARRIVAL,ARRIVAL_TIME,
       ARRIVAL_DELAY,CANCELLATION_REASON
FROM FLIGHTS
WHERE DEPARTURE_TIME IS NOT NULL AND DEPARTURE_DELAY IS NULL OR ARRIVAL_DELAY IS NULL
      AND ARRIVAL_TIME IS NOT NULL;

--HANDLING DATE TIME DATATYPES
ALTER TABLE FLIGHTS
ADD COLUMN FLIGHT_DATE DATE;

UPDATE FLIGHTS
SET FLIGHT_DATE=MAKE_DATE(YEAR,MONTH,DAY);


--Adding necessary columns
ALTER TABLE FLIGHTS
ADD COLUMN SCHEDULED_ARRIVALS TIMESTAMP,
ADD COLUMN ARRIVALS_TIME TIMESTAMP,
ADD COLUMN SCHEDULED_DEPARTURES TIMESTAMP,
ADD COLUMN DEPARTURES_TIME TIMESTAMP,
ADD COLUMN ARRIVALS_DELAY INT,
ADD COLUMN DEPARTURES_DELAY INT,
ADD COLUMN CANCELLATION_REASON_DESC VARCHAR;


--Dealing with delay columns 
--ARRIVAL DELAY
UPDATE FLIGHTS
SET SCHEDULED_ARRIVALS=FLIGHT_DATE+SCHEDULED_ARRIVAL,ARRIVALS_TIME=FLIGHT_DATE+ARRIVAL_TIME,
    DEPARTURES_TIME=FLIGHT_DATE+DEPARTURE_TIME,SCHEDULED_DEPARTURES=FLIGHT_DATE+SCHEDULED_DEPARTURE;

UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=23 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=00;

UPDATE FLIGHTS
SET SCHEDULED_ARRIVALS=FLIGHT_DATE+INTERVAL'1 DAY'+SCHEDULED_ARRIVAL
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=01 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=23;

UPDATE FLIGHTS
SET SCHEDULED_ARRIVALS=FLIGHT_DATE+INTERVAL'1 DAY'+SCHEDULED_ARRIVAL
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=00 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=22;

UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=23 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=01;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=23 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=02;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=23 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=03;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=23 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=04;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=23 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=05;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=23 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=06;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=23 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=07;

UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=23 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=08;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=23 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=09;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=23 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=10;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=23 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=11;

UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=23 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=12;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=23 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=13;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=23 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=14;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=23 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=15;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=23 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=16;
 
 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=22 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=00;

  UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=22 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=01;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=22 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=02;

  UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=22 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=03;

  UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=22 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=04;

  UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=22 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=05;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=22 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=06;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=22 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=07;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=22 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=08;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=22 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=09;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=22 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=10;

  UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=22 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=11;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=22 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=12;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=22 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=13;

  UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=22 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=14;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=22 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=15;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=22 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=16;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=22 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=17;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=22 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=18;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=21 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=00;
 
 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=21 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=01;
 
 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=21 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=02;
 
 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=21 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=03;
 
 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=21 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=04;
 
 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=21 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=05;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=21 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=06;
 
 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=21 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=07;
 
 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=21 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=08;
 
 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=21 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=09;
 
 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=21 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=10;
 
 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=21 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=11;
 
 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=21 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=12;
 
 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=21 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=13;
 
 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=21 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=14;
 
 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=21 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=15;
 
 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=21 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=16;
 
 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=21 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=17;
 
UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=21 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=18;
 
UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=20 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=00;
 
UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=20 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=01;
 
 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=20 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=02;
 
UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=20 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=03;
 
UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=20 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=04;
 
UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=20 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=05;
 
 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=20 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=06;
 
 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=20 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=07;
 
 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=20 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=08;
 
 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=20 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=09;
 
 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=20 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=10;
 
 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=20 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=11;
 
 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=20 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=12;
 
 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=20 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=13;
 
 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=20 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=14;
 
 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=20 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=15;

UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=20 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=16;
 
 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=20 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=17;
 
  UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=19 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=00;
 
  UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=19 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=01;
 
   UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=19 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=02;
 
   UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=19 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=03;
 
   UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=19 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=04;
 
   UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=19 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=05;
 
   UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=19 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=06;
 
   UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=19 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=07;
 
   UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=19 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=08;
 
   UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=19 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=09;
 
   UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=19 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=10;
 
   UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=19 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=11;
 
   UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=19 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=12;
 
   UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=19 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=13;
 
   UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=19 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=14;
 
   UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=19 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=15;
 
   UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=19 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=16;
 
   UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=19 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=17;
 
   UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=19 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=18;
 
  UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=18 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=00;
 
  UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=18 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=01;
 
  UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=18 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=02;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=18 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=03;

  UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=18 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=04;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=18 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=05;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=18 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=06;

  UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=18 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=07;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=18 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=08;

  UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=18 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=09;

  UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=18 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=10;

  UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=18 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=11;

  UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=18 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=12;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=18 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=13;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=18 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=14;

  UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=18 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=15;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=17 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=00;

  UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=17 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=01;

  UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=17 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=02;

  UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=17 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=03;

  UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=17 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=04;

  UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=17 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=05;

  UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=17 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=06;

  UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=17 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=07;

  UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=17 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=08;

  UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=17 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=09;

  UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=17 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=10;

  UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=17 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=11;

  UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=17 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=12;

  UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=17 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=13;

  UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=17 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=14;

  UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=17 
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=15;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=16
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=00;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=16
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=01;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=16
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=02;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=16
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=03;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=16
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=04;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=16
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=05;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=16
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=07;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=16
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=08;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=16
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=09;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=16
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=10;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=16
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=11;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=16
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=12;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=16
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=13;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=16
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=14;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=15
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=00;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=15
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=01;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=15
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=02;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=15
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=03;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=15
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=04;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=15
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=05;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=15
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=06;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=15
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=07;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=15
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=08;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=15
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=09;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=15
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=10;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=15
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=11;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=15
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=12;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=15
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=13;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=14
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=00;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=14
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=01;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=14
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=02;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=14
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=03;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=14
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=04;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=14
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=05;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=14
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=06;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=14
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=07;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=14
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=08;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=14
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=09;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=14
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=10;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=14
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=11;

UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=13
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=00;

UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=13
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=01;

UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=13
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=02;

UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=13
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=03;

UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=13
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=04;

UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=13
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=05;

UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=13
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=06;

UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=13
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=07;

UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=13
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=08;

UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=13
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=09;

UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=13
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=10;

UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=13
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=11;

UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=12
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=00;

UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=12
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=01;

UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=12
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=02;

UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=12
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=03;

UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=12
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=04;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=12
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=05;

UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=12
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=06;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=12
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=07;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=12
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=08;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=12
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=09;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=11
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=00;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=11
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=00;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=11
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=01;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=11
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=02;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=11
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=03;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=11
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=04;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=11
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=07;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=11
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=08;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=11
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=09;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=10
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=00;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=10
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=01;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=10
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=02;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=10
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=03;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=10
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=07;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=09
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=00;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=09
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=01;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=09
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=02;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=09
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=03;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=09
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=04;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=08
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=00;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=08
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=01;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=08
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=02;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=08
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=06;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=08
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=05;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=07
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=00;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=07
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=01;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=07
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=02;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=06
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=00;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=06
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=02;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=06
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=03;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=05
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=00;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=05
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=03;

 UPDATE FLIGHTS
SET ARRIVALS_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+ARRIVAL_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_ARRIVAL)=04
 AND EXTRACT(HOUR FROM ARRIVAL_TIME)=00;

UPDATE FLIGHTS
SET ARRIVALS_DELAY=CAST(EXTRACT(EPOCH FROM (ARRIVALS_TIME-SCHEDULED_ARRIVALS))/60 AS INT)
WHERE ARRIVAL_TIME IS NOT NULL;


--DEPARTURE DELAY
 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=00
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=23;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=00
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=22;

  UPDATE FLIGHTS
SET SCHEDULED_DEPARTURES=FLIGHT_DATE+INTERVAL'1 DAY'+SCHEDULED_DEPARTURE
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=00
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=23;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=23
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=00;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=23
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=01;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=23
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=02;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=23
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=03;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=23
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=04;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=23
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=05;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=23
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=06;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=23
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=07;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=23
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=08;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=23
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=09;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=23
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=10;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=23
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=11;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=23
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=12;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=23
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=13;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=23
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=14;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=23
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=17;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=23
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=18;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=22
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=00;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=22
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=01;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=22
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=02;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=22
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=03;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=22
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=04;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=22
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=05;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=22
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=06;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=22
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=07;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=22
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=08;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=22
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=09;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=22
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=10;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=22
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=11;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=22
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=12;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=22
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=13;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL '1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=22
AND EXTRACT (HOUR FROM DEPARTURE_TIME)=15;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=21
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=00;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=21
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=01;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=21
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=02;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=21
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=03;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=21
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=04;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=21
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=05;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=21
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=06;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=21
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=07;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=21
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=08;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=21
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=09;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=21
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=10;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=21
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=11;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=21
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=12;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=21
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=13;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL '1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=21
AND EXTRACT (HOUR FROM DEPARTURE_TIME)=15;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL '1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=21
AND EXTRACT (HOUR FROM DEPARTURE_TIME)=14;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL '1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=21
AND EXTRACT (HOUR FROM DEPARTURE_TIME)=16;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=20
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=00;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=20
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=01;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=20
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=02;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=20
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=03;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=20
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=04;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=20
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=05;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=20
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=06;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=20
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=07;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=20
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=08;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=20
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=09;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=20
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=10;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=20
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=11;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=20
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=12;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=20
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=13;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL '1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=20
AND EXTRACT (HOUR FROM DEPARTURE_TIME)=15;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL '1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=20
AND EXTRACT (HOUR FROM DEPARTURE_TIME)=14;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL '1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=20
AND EXTRACT (HOUR FROM DEPARTURE_TIME)=17;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=19
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=00;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=19
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=01;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=19
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=02;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=19
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=03;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=19
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=04;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=19
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=05;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=19
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=06;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=19
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=07;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=19
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=08;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=19
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=09;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=19
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=10;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=19
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=11;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=19
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=12;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=19
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=13;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL '1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=19
AND EXTRACT (HOUR FROM DEPARTURE_TIME)=15;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL '1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=19
AND EXTRACT (HOUR FROM DEPARTURE_TIME)=14;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=19
AND EXTRACT (HOUR FROM DEPARTURE_TIME)=18;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=18
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=00;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=18
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=01;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=18
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=02;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=18
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=03;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=18
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=04;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=18
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=05;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=18
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=06;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=18
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=07;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=18
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=08;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=18
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=09;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=18
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=10;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=18
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=11;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=18
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=12;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=18
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=13;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL '1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=18
AND EXTRACT (HOUR FROM DEPARTURE_TIME)=15;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL '1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=18
AND EXTRACT (HOUR FROM DEPARTURE_TIME)=14;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL '1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=19
AND EXTRACT (HOUR FROM DEPARTURE_TIME)=16;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=17
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=00;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=17
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=01;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=17
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=02;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=17
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=03;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=17
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=04;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=17
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=05;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=17
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=06;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=17
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=07;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=17
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=08;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=17
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=09;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=17
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=10;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=17
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=11;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=17
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=12;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=17
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=13;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL '1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=17
AND EXTRACT (HOUR FROM DEPARTURE_TIME)=14;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=16
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=00;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=16
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=01;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=16
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=02;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=16
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=03;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=16
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=04;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=16
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=05;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=16
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=06;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=16
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=07;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=16
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=08;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=16
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=09;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=16
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=10;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=16
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=11;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=16
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=12;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=15
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=00;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=15
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=01;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=15
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=02;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=15
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=03;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=15
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=04;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=15
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=05;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=15
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=06;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=15
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=07;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=15
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=08;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=15
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=09;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=15
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=10;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=15
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=11;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=15
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=12;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=14
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=00;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=14
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=01;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=14
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=02;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=14
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=03;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=14
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=04;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=14
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=05;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=14
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=06;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=14
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=07;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=14
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=08;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=14
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=09;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=14
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=10;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=14
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=11;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=14
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=12;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=13
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=00;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=13
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=01;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=13
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=02;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=13
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=03;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=13
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=04;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=13
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=05;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=13
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=06;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=13
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=07;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=13
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=08;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=13
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=09;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=13
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=10;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=13
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=11;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=12
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=00;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=12
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=01;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=12
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=02;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=12
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=03;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=12
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=04;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=12
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=05;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=12
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=06;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=12
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=07;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=12
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=08;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=12
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=09;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=12
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=10;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=11
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=00;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=11
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=01;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=11
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=02;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=11
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=03;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=11
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=04;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=11
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=05;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=11
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=06;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=11
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=07;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=11
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=08;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=11
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=09;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=11
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=10;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=10
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=00;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=10
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=01;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=10
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=02;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=10
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=03;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=10
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=04;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=10
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=05;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=10
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=06;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=10
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=07;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=10
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=08;



 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=09
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=01;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=09
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=02;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=09
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=03;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=09
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=04;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=09
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=05;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=09
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=06;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=09
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=07;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=08
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=00;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=08
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=05;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=08
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=06;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=07
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=00;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL '1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=07
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=05;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=06
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=00;

 UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=06
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=01;

UPDATE FLIGHTS
SET DEPARTURES_TIME=FLIGHT_DATE+INTERVAL'1 DAY'+DEPARTURE_TIME
WHERE EXTRACT(HOUR FROM SCHEDULED_DEPARTURE)=05
 AND EXTRACT(HOUR FROM DEPARTURE_TIME)=00;


UPDATE FLIGHTS
SET DEPARTURES_DELAY=CAST(EXTRACT(EPOCH FROM (DEPARTURES_TIME-SCHEDULED_DEPARTURES))/60 AS INT)
WHERE DEPARTURE_TIME IS NOT NULL;

--CANCELATION_REASON_DESCRIPTION
UPDATE FLIGHTS
SET CANCELLATION_REASON_DESC=CASE WHEN CANCELLATION_REASON='A' THEN 'CARRIER/AIRLINE OPERATION' 
                                  WHEN CANCELLATION_REASON='B' THEN 'WEATHER'   
                                  WHEN CANCELLATION_REASON='C' THEN 'NATIONAL AIRSPACE SYSTEM(ATC)'
								  WHEN CANCELLATION_REASON='D' THEN 'SECURITY' 
								  ELSE 'NA' END;


SELECT*FROM FLIGHTS;

--DELETING UNWANTED ROWS AND COLUMNS
DELETE FROM FLIGHTS
WHERE ARRIVAL_DELAY != ARRIVALS_DELAY;

DELETE FROM FLIGHTS
WHERE DEPARTURE_DELAY != DEPARTURES_DELAY;

ALTER TABLE FLIGHTS
DROP COLUMN ARRIVAL_DELAY,
DROP COLUMN DEPARTURE_DELAY,
DROP COLUMN SCHEDULED_ARRIVAL,
DROP COLUMN SCHEDULED_DEPARTURE,
DROP COLUMN ARRIVAL_TIME,
DROP COLUMN DEPARTURE_TIME;

--DATA INTEGRATION(UNIFIED TABLE)
DROP TABLE UNIFIED_FLIGHT;
CREATE TABLE UNIFIED_FLIGHT AS
       SELECT F.*,A.AIRPORT AS AIRPORT_NAME,A.CITY,A.STATE,A.LATITUDE,A.LONGITUDE,
	          L.AIRLINE AS AIRLINE_NAME FROM FLIGHTS AS F
	   LEFT JOIN AIRLINES AS L
	        ON F.AIRLINE=L.IATA_CODE
	         LEFT JOIN AIRPORTS AS A
			      ON F.ORIGIN_AIRPORT=A.IATA_CODE; 

SELECT*FROM UNIFIED_FLIGHT;



---EXPLORATORY DATA ANALYSIS (EDA) AND KPI DEFINITION---
--OVERALL FLIGHT VOLUME
SELECT COUNT(AIRLINE) AS OVERALL_FLIGHT_VOLUME  FROM UNIFIED_FLIGHT;
--FLIGHT VOLUME BY AIRLINE
SELECT AIRLINE,AIRLINE_NAME,COUNT(AIRLINE) AS FLIGHT_VOL_AIRLINE FROM UNIFIED_FLIGHT
GROUP BY 1,2;
--FLIGHT VOLUME BY MONTH
SELECT MONTH,COUNT(*)  AS FLIGHT_VOL_MONTH FROM UNIFIED_FLIGHT
WHERE ARRIVALS_TIME IS NOT NULL
GROUP  BY 1;
--FLIGHT VOLUME BY AIRPORT
SELECT ORIGIN_AIRPORT,COUNT(ORIGIN_AIRPORT) AS FLIGHT_VOL_AIRPORT
FROM UNIFIED_FLIGHT
WHERE ARRIVALS_TIME IS NOT NULL
GROUP BY 1;

--TOTAL CANCELLED FLIGHTS
SELECT COUNT(CANCELLATION_REASON) AS CANCELLED_FLIGHTS
FROM UNIFIED_FLIGHT
WHERE CANCELLATION_REASON !='NA';
--CANCELLATION BY REASON
SELECT CANCELLATION_REASON,CANCELLATION_REASON_DESC,COUNT(CANCELLATION_REASON) AS CANCELLED_FLIGHTS
FROM UNIFIED_FLIGHT
WHERE CANCELLATION_REASON!='NA'
GROUP BY 1,2;

--FLIGHTS DIVERTED
SELECT SUM(DIVERTED) AS TOTAL_FLIGHT_DIVERTED FROM UNIFIED_FLIGHT;
--FLIGHT NOT DIVERTED
SELECT COUNT(DIVERTED) AS NON_DIVERTED FROM UNIFIED_FLIGHT
WHERE DIVERTED=0;


--STATISTICS FOR DEPARTURE AND ARRIVAL DELAYS
--DEPARTURE DELAY
SELECT AVG(DEPARTURES_DELAY) AS AVERAGE_DEP_DELAY,MAX(DEPARTURES_DELAY) AS MAXIMUM_DEP_DELAY,
       PERCENTILE_CONT(0.5)WITHIN GROUP(ORDER BY DEPARTURES_DELAY) AS MEDIAN_DEPARTURE_DELAY,
	   MIN(DEPARTURES_DELAY) AS MINIMUM_DEP_DELAY
FROM UNIFIED_FLIGHT;
--DELAYED DEPARTURES
SELECT ROUND(AVG(DEPARTURES_DELAY),2) AS AVERAGE_DEP_DELAY,MAX(DEPARTURES_DELAY) AS MAXIMUM_DEP_DELAY,
       PERCENTILE_CONT(0.5)WITHIN GROUP(ORDER BY DEPARTURES_DELAY) AS MEDIAN_DEPARTURE_DELAY,
	   MIN(DEPARTURES_DELAY) AS MINIMUM_DEP_DELAY
FROM UNIFIED_FLIGHT
WHERE DEPARTURES_DELAY>0;
--EARLY DEPARTURES
SELECT ROUND(AVG(DEPARTURES_DELAY),2) AS AVERAGE_EARLY_FLIGHT,MAX(DEPARTURES_DELAY) AS MINIMUM_EARLY_FLIGHT,
       PERCENTILE_CONT(0.5)WITHIN GROUP(ORDER BY DEPARTURES_DELAY) AS MEDIAN_EARLY_FLIGHT,
	   MIN(DEPARTURES_DELAY) AS MAXIMUM_EARLY_FLIGHT
FROM UNIFIED_FLIGHT
WHERE DEPARTURES_DELAY<0;
--ONTIME DEPARTURE
SELECT COUNT(DEPARTURES_DELAY) AS ONTIME_DEPARTURES
FROM UNIFIED_FLIGHT
WHERE DEPARTURES_DELAY=0 AND DEPARTURES_DELAY IS NOT NULL;
--DELAYED FLIGHT DEPARTURES
SELECT COUNT(DEPARTURES_DELAY) AS DELAYED_FLIGHTS
FROM UNIFIED_FLIGHT
WHERE DEPARTURES_DELAY>0 AND DEPARTURES_DELAY IS NOT NULL;

--ARRIVAL DELAY
SELECT ROUND(AVG(ARRIVALS_DELAY),2) AS AVERAGE_ARRIVAL_DELAY,MAX(ARRIVALS_DELAY) AS MAXIMUM_ARR_DELAY,
       PERCENTILE_CONT(0.5)WITHIN GROUP(ORDER BY ARRIVALS_DELAY) AS MEDIAN_ARRIVAL_DELAY,
	   MIN(ARRIVALS_DELAY) AS MINIMUM_ARRIVAL_DELAY
FROM UNIFIED_FLIGHT;
--DELAYED ARRIVALS
SELECT ROUND(AVG(ARRIVALS_DELAY),2) AS AVERAGE_ARRIVAL_DELAY,MAX(ARRIVALS_DELAY) AS MAXIMUM_ARR_DELAY,
       PERCENTILE_CONT(0.5)WITHIN GROUP(ORDER BY ARRIVALS_DELAY) AS MEDIAN_ARRIVAL_DELAY,
	   MIN(ARRIVALS_DELAY) AS MINIMUM_ARRIVAL_DELAY
FROM UNIFIED_FLIGHT
WHERE ARRIVALS_DELAY>0;
--EARLY ARRIVALS
SELECT ROUND(AVG(ARRIVALS_DELAY),2) AS AVERAGE_EARLY_ARRIVAL,MAX(ARRIVALS_DELAY) AS MINIMUM_EARLY_ARRIVAL,
       PERCENTILE_CONT(0.5)WITHIN GROUP(ORDER BY ARRIVALS_DELAY) AS MEDIAN_EARLY_ARRIVAL,
	   MIN(ARRIVALS_DELAY) AS MAXIMUM_EARLY_ARRIVAL
FROM UNIFIED_FLIGHT
WHERE ARRIVALS_DELAY<0;
--ONTIME ARRIVALS
SELECT COUNT(ARRIVALS_DELAY) AS ONTIME_FLIGHTS
FROM UNIFIED_FLIGHT
WHERE ARRIVALS_DELAY=0 AND ARRIVALS_DELAY IS NOT NULL;
--DELAYED FLIGHT ARRIVALS
SELECT COUNT(ARRIVALS_DELAY) AS ONTIME_FLIGHTS
FROM UNIFIED_FLIGHT
WHERE ARRIVALS_DELAY>0  AND ARRIVALS_DELAY IS NOT NULL;



--DISTRIBUTION OF DIFFERENT TYPE OF DELAY
--AIR SYSTEM DELAY
SELECT ROUND(AVG(AIR_SYSTEM_DELAY),2) AS AVERAGE_AIRSYSYTEM_DELAY,
       MAX(AIR_SYSTEM_DELAY) AS MAX_DELAY,MIN(AIR_SYSTEM_DELAY) AS MIN_DELAY,
	   PERCENTILE_CONT(0.5)WITHIN GROUP (ORDER BY AIR_SYSTEM_DELAY) AS MEDIAN_DELAY
FROM UNIFIED_FLIGHT
WHERE AIR_SYSTEM_DELAY>0;
--NO AIR SYSTEM DELAY
SELECT COUNT(*) AS NO_AIR_SYS_DELAY FROM UNIFIED_FLIGHT
WHERE AIR_SYSTEM_DELAY=0;
--SECURITY DELAY
SELECT ROUND(AVG(SECURITY_DELAY),2) AS AVERAGE_SECURITY_DELAY,
       MAX(SECURITY_DELAY) AS MAX_DELAY,MIN(SECURITY_DELAY) AS MIN_DELAY,
	   PERCENTILE_CONT(0.5)WITHIN GROUP (ORDER BY SECURITY_DELAY) AS MEDIAN_DELAY
FROM UNIFIED_FLIGHT
WHERE SECURITY_DELAY>0;
--NO SECURITY DELAY
SELECT COUNT(*) AS NO_SECURITY_DELAY FROM UNIFIED_FLIGHT
WHERE SECURITY_DELAY=0;
--AIRLINE DELAY
SELECT ROUND(AVG(AIRLINE_DELAY),2) AS AVERAGE_AIRLINE_DELAY,
       MAX(AIRLINE_DELAY) AS MAX_DELAY,MIN(AIRLINE_DELAY) AS MIN_DELAY,
	   PERCENTILE_CONT(0.5)WITHIN GROUP (ORDER BY AIRLINE_DELAY) AS MEDIAN_DELAY
FROM UNIFIED_FLIGHT
WHERE AIRLINE_DELAY>0;
--NO AIRLINE DELAY
SELECT COUNT(*) AS NO_AIRLINE_DELAY FROM UNIFIED_FLIGHT
WHERE AIRLINE_DELAY=0;
--LATE AIRCRAFT DELAY
SELECT ROUND(AVG(LATE_AIRCRAFT_DELAY),2) AS AVERAGE_AIRCRAFT_DELAY,
       MAX(LATE_AIRCRAFT_DELAY) AS MAX_DELAY,MIN(LATE_AIRCRAFT_DELAY) AS MIN_DELAY,
	   PERCENTILE_CONT(0.5)WITHIN GROUP (ORDER BY LATE_AIRCRAFT_DELAY) AS MEDIAN_DELAY
FROM UNIFIED_FLIGHT
WHERE LATE_AIRCRAFT_DELAY>0;
--NO AIR SYSTEM DELAY
SELECT COUNT(*) AS NO_AIRCRAFT_DELAY FROM UNIFIED_FLIGHT
WHERE LATE_AIRCRAFT_DELAY=0;
--WEATHER DELAY
SELECT ROUND(AVG(WEATHER_DELAY),2) AS AVERAGE_WEATHER_DELAY,
       MAX(WEATHER_DELAY) AS MAX_DELAY,MIN(WEATHER_DELAY) AS MIN_DELAY,
	   PERCENTILE_CONT(0.5)WITHIN GROUP (ORDER BY WEATHER_DELAY) AS MEDIAN_DELAY
FROM UNIFIED_FLIGHT
WHERE WEATHER_DELAY>0;
--NO WEATHER DELAY
SELECT COUNT(*) AS NO_WEATHER_DELAY FROM UNIFIED_FLIGHT
WHERE WEATHER_DELAY=0;


--DEFINE KPI
--ON TIME PERFORMANCE RATE
WITH ONTIME AS (
      SELECT COUNT(*) AS ONTIMEFLIGHTS
	  FROM UNIFIED_FLIGHT
	  WHERE ARRIVALS_DELAY<15 AND ARRIVALS_TIME IS NOT NULL),
	TOTAL AS( SELECT COUNT(*)AS TOTAL_FLIGHTS
	          FROM UNIFIED_FLIGHT
			  WHERE ARRIVALS_TIME IS NOT NULL)
SELECT ROUND((O.ONTIMEFLIGHTS :: NUMERIC/T.TOTAL_FLIGHTS)*100,2) AS ON_TIME_PERFORMANCE_RATE
FROM ONTIME AS O,TOTAL AS T;
 
--AVERAGE ARRIVAL DELAY
SELECT ROUND(AVG(ARRIVALS_DELAY),2) AS AVERAGE_ARRIVAL_DELAY
FROM UNIFIED_FLIGHT
WHERE ARRIVALS_DELAY>0 AND ARRIVALS_DELAY IS NOT NULL;
--AVERAGE DEPARTURE DELAY
SELECT ROUND(AVG(DEPARTURES_DELAY),2) AS AVERAGE_DEPARTURE_DELAY
FROM UNIFIED_FLIGHT
WHERE DEPARTURES_DELAY>0 AND DEPARTURES_DELAY IS NOT NULL;

--CANCELLATION RATE
WITH CANCELLATION AS ( SELECT COUNT(CANCELLATION_REASON) AS CANCELLED FROM UNIFIED_FLIGHT
                       WHERE CANCELLATION_REASON !='NA'),
	 TOTAL AS (SELECT COUNT(*) AS TOTALS FROM UNIFIED_FLIGHT)
SELECT ROUND((C.CANCELLED::NUMERIC/T.TOTALS)*100,2) AS CANCELLATION_RATE
FROM CANCELLATION AS C,TOTAL AS T;

--PERCENTAGE CONTRIBUTION OF EACH DELAY TYPE
WITH CONTRIBUTION AS(SELECT CANCELLATION_REASON,COUNT(CANCELLATION_REASON) AS RATE
                     FROM UNIFIED_FLIGHT
					 WHERE CANCELLATION_REASON !='NA'
					 GROUP BY 1),
TOTALS AS (SELECT COUNT(CANCELLATION_REASON) AS TOTALS FROM UNIFIED_FLIGHT
           WHERE CANCELLATION_REASON!='NA')
SELECT C.CANCELLATION_REASON,ROUND((C.RATE::NUMERIC/T.TOTALS)*100,2) AS PERCENTAGE_CONTRIBUTION
FROM CONTRIBUTION AS C,TOTALS AS T;

--PERFORM INITIAL AGGREGATION BY:
--AIRLINE--ON TIME PERFORMANCE RATE
WITH ONTIME AS (
      SELECT AIRLINE,COUNT(*) AS ONTIMEFLIGHTS
	  FROM UNIFIED_FLIGHT
	  WHERE ARRIVALS_DELAY<15 AND ARRIVALS_TIME IS NOT NULL
	  GROUP BY 1),
	TOTALS AS( SELECT COUNT(*)AS TOTAL_FLIGHTS
	          FROM UNIFIED_FLIGHT
			  WHERE ARRIVALS_TIME IS NOT NULL)
SELECT O.AIRLINE,ROUND((O.ONTIMEFLIGHTS :: NUMERIC/T1.TOTAL_FLIGHTS)*100,2) AS ON_TIME_PERFORMANCE_RATE
FROM ONTIME AS O,TOTALS AS T1;
--AIRLINE--ARRIVAL DELAY
SELECT AIRLINE,ROUND(AVG(ARRIVALS_DELAY),2) AS AVERAGE_ARRIVAL_DELAY
                 FROM UNIFIED_FLIGHT
                  WHERE ARRIVALS_DELAY>0 AND ARRIVALS_DELAY IS NOT NULL
                 GROUP BY 1;
--AIRLINE--DEPARTURE DELAY
SELECT AIRLINE,ROUND(AVG(DEPARTURES_DELAY),2) AS AVERAGE_DEPARTURE_DELAY
                 FROM UNIFIED_FLIGHT
                 WHERE DEPARTURES_DELAY>0 AND DEPARTURES_DELAY IS NOT NULL
                 GROUP BY 1;
--AIRLINE----CANCELLATION RATE
WITH CANCELLATION AS ( SELECT AIRLINE, COUNT(CANCELLATION_REASON) AS CANCELLED FROM UNIFIED_FLIGHT
                       WHERE CANCELLATION_REASON !='NA'
					   GROUP BY 1),
	 TOTAL AS (SELECT COUNT(*) AS TOTALS FROM UNIFIED_FLIGHT)
SELECT C.AIRLINE,ROUND((C.CANCELLED::NUMERIC/T.TOTALS)*100,2) AS CANCELLATION_RATE
FROM CANCELLATION AS C,TOTAL AS T;
--AIRLINE--PERCENTAGE CONTRIBUTION OF EACH DELAY TYPE
WITH CONTRIBUTION AS(SELECT AIRLINE,CANCELLATION_REASON,COUNT(CANCELLATION_REASON) AS RATE
                     FROM UNIFIED_FLIGHT
					 WHERE CANCELLATION_REASON !='NA'
					 GROUP BY 1,2),
TOTALS AS (SELECT COUNT(CANCELLATION_REASON) AS TOTALS FROM UNIFIED_FLIGHT
           WHERE CANCELLATION_REASON!='NA')
SELECT C.AIRLINE,C.CANCELLATION_REASON,ROUND((C.RATE::NUMERIC/T.TOTALS)*100,2) AS PERCENTAGE_CONTRIBUTION
FROM CONTRIBUTION AS C,TOTALS AS T;

--AIRPORT--ON TIME PERFORMANCE RATE
WITH ONTIME AS (
      SELECT ORIGIN_AIRPORT AS AIRPORT,COUNT(*) AS ONTIMEFLIGHTS
	  FROM UNIFIED_FLIGHT
	  WHERE ARRIVALS_DELAY<15 AND ARRIVALS_TIME IS NOT NULL
	  GROUP BY 1),
	TOTALS AS( SELECT COUNT(*)AS TOTAL_FLIGHTS
	          FROM UNIFIED_FLIGHT
			  WHERE ARRIVALS_TIME IS NOT NULL)
SELECT O.AIRPORT,ROUND((O.ONTIMEFLIGHTS :: NUMERIC/T1.TOTAL_FLIGHTS)*100,2) AS ON_TIME_PERFORMANCE_RATE
FROM ONTIME AS O,TOTALS AS T1
order by 2 desc;
--AIRPORT--ARRIVAL DELAY
SELECT ORIGIN_AIRPORT AS AIRPORT,ROUND(AVG(ARRIVALS_DELAY),2) AS AVERAGE_ARRIVAL_DELAY
                 FROM UNIFIED_FLIGHT
                  WHERE ARRIVALS_DELAY>0 AND ARRIVALS_DELAY IS NOT NULL
                 GROUP BY 1;
--AIRPORT--DEPARTURE DELAY
SELECT ORIGIN_AIRPORT AS AIRPORT,ROUND(AVG(DEPARTURES_DELAY),2) AS AVERAGE_DEPARTURE_DELAY
                 FROM UNIFIED_FLIGHT
                 WHERE DEPARTURES_DELAY>0 AND DEPARTURES_DELAY IS NOT NULL
                 GROUP BY 1;
--AIRPORT----CANCELLATION RATE
WITH CANCELLATION AS ( SELECT ORIGIN_AIRPORT AS AIRPORT, COUNT(CANCELLATION_REASON) AS CANCELLED FROM UNIFIED_FLIGHT
                       WHERE CANCELLATION_REASON !='NA'
					   GROUP BY 1),
	 TOTAL AS (SELECT COUNT(*) AS TOTALS FROM UNIFIED_FLIGHT)
SELECT C.AIRPORT,ROUND((C.CANCELLED::NUMERIC/T.TOTALS)*100,2) AS CANCELLATION_RATE
FROM CANCELLATION AS C,TOTAL AS T
ORDER BY 2 DESC;
--AIRPORT--PERCENTAGE CONTRIBUTION OF EACH DELAY TYPE
WITH CONTRIBUTION AS(SELECT ORIGIN_AIRPORT AS AIRPORT,CANCELLATION_REASON,
                            COUNT(CANCELLATION_REASON) AS RATE
                     FROM UNIFIED_FLIGHT
					 WHERE CANCELLATION_REASON !='NA'
					 GROUP BY 1,2),
TOTALS AS (SELECT COUNT(CANCELLATION_REASON) AS TOTALS FROM UNIFIED_FLIGHT
           WHERE CANCELLATION_REASON!='NA')
SELECT C.AIRPORT,C.CANCELLATION_REASON,ROUND((C.RATE::NUMERIC/T.TOTALS)*100,2) AS PERCENTAGE_CONTRIBUTION
FROM CONTRIBUTION AS C,TOTALS AS T;

--MONTH--ON TIME PERFORMANCE RATE
WITH ONTIME AS (
      SELECT MONTH,COUNT(*) AS ONTIMEFLIGHTS
	  FROM UNIFIED_FLIGHT
	  WHERE ARRIVALS_DELAY<15 AND ARRIVALS_TIME IS NOT NULL
	  GROUP BY 1),
	TOTALS AS( SELECT COUNT(*)AS TOTAL_FLIGHTS
	          FROM UNIFIED_FLIGHT
			  WHERE ARRIVALS_TIME IS NOT NULL)
SELECT O.MONTH,ROUND((O.ONTIMEFLIGHTS :: NUMERIC/T1.TOTAL_FLIGHTS)*100,2) AS ON_TIME_PERFORMANCE_RATE
FROM ONTIME AS O,TOTALS AS T1;
--MONTH--ARRIVAL DELAY
SELECT MONTH,ROUND(AVG(ARRIVALS_DELAY),2) AS AVERAGE_ARRIVAL_DELAY
                 FROM UNIFIED_FLIGHT
                  WHERE ARRIVALS_DELAY>0 AND ARRIVALS_DELAY IS NOT NULL
                 GROUP BY 1;
--MONTH--DEPARTURE DELAY
SELECT MONTH,ROUND(AVG(DEPARTURES_DELAY),2) AS AVERAGE_DEPARTURE_DELAY
                 FROM UNIFIED_FLIGHT
                 WHERE DEPARTURES_DELAY>0 AND DEPARTURES_DELAY IS NOT NULL
                 GROUP BY 1;
--MONTH--CANCELLATION RATE
WITH CANCELLATION AS ( SELECT MONTH, COUNT(CANCELLATION_REASON) AS CANCELLED FROM UNIFIED_FLIGHT
                       WHERE CANCELLATION_REASON !='NA'
					   GROUP BY 1),
	 TOTAL AS (SELECT COUNT(*) AS TOTALS FROM UNIFIED_FLIGHT)
SELECT C.MONTH,ROUND((C.CANCELLED::NUMERIC/T.TOTALS)*100,2) AS CANCELLATION_RATE
FROM CANCELLATION AS C,TOTAL AS T;
--MONTH--PERCENTAGE CONTRIBUTION OF EACH DELAY TYPE
WITH CONTRIBUTION AS(SELECT MONTH,CANCELLATION_REASON,COUNT(CANCELLATION_REASON) AS RATE
                     FROM UNIFIED_FLIGHT
					 WHERE CANCELLATION_REASON !='NA'
					 GROUP BY 1,2),
TOTALS AS (SELECT COUNT(CANCELLATION_REASON) AS TOTALS FROM UNIFIED_FLIGHT
           WHERE CANCELLATION_REASON!='NA')
SELECT C.MONTH,C.CANCELLATION_REASON,ROUND((C.RATE::NUMERIC/T.TOTALS)*100,2) AS PERCENTAGE_CONTRIBUTION
FROM CONTRIBUTION AS C,TOTALS AS T;

--DAY OF WEEK--ON TIME PERFORMANCE RATE
WITH ONTIME AS (
      SELECT DAY_OF_WEEK,COUNT(*) AS ONTIMEFLIGHTS
	  FROM UNIFIED_FLIGHT
	  WHERE ARRIVALS_DELAY<15 AND ARRIVALS_TIME IS NOT NULL
	  GROUP BY 1),
	TOTALS AS( SELECT COUNT(*)AS TOTAL_FLIGHTS
	          FROM UNIFIED_FLIGHT
			  WHERE ARRIVALS_TIME IS NOT NULL)
SELECT O.DAY_OF_WEEK,ROUND((O.ONTIMEFLIGHTS :: NUMERIC/T1.TOTAL_FLIGHTS)*100,2) AS ON_TIME_PERFORMANCE_RATE
FROM ONTIME AS O,TOTALS AS T1;
--DAY OF WEEK--ARRIVAL DELAY
SELECT DAY_OF_WEEK,ROUND(AVG(ARRIVALS_DELAY),2) AS AVERAGE_ARRIVAL_DELAY
                 FROM UNIFIED_FLIGHT
                  WHERE ARRIVALS_DELAY>0 AND ARRIVALS_DELAY IS NOT NULL
                 GROUP BY 1;
--DAY OF WEEK--DEPARTURE DELAY
SELECT DAY_OF_WEEK,ROUND(AVG(DEPARTURES_DELAY),2) AS AVERAGE_DEPARTURE_DELAY
                 FROM UNIFIED_FLIGHT
                 WHERE DEPARTURES_DELAY>0 AND DEPARTURES_DELAY IS NOT NULL
                 GROUP BY 1;
--DAY OF WEEK----CANCELLATION RATE
WITH CANCELLATION AS ( SELECT DAY_OF_WEEK, COUNT(CANCELLATION_REASON) AS CANCELLED FROM UNIFIED_FLIGHT
                       WHERE CANCELLATION_REASON !='NA'
					   GROUP BY 1),
	 TOTAL AS (SELECT COUNT(*) AS TOTALS FROM UNIFIED_FLIGHT)
SELECT C.DAY_OF_WEEK,ROUND((C.CANCELLED::NUMERIC/T.TOTALS)*100,2) AS CANCELLATION_RATE
FROM CANCELLATION AS C,TOTAL AS T;
--DAY OF WEEK--PERCENTAGE CONTRIBUTION OF EACH DELAY TYPE
WITH CONTRIBUTION AS(SELECT DAY_OF_WEEK,CANCELLATION_REASON,COUNT(CANCELLATION_REASON) AS RATE
                     FROM UNIFIED_FLIGHT
					 WHERE CANCELLATION_REASON !='NA'
					 GROUP BY 1,2),
TOTALS AS (SELECT COUNT(CANCELLATION_REASON) AS TOTALS FROM UNIFIED_FLIGHT
           WHERE CANCELLATION_REASON!='NA')
SELECT C.DAY_OF_WEEK,C.CANCELLATION_REASON,ROUND((C.RATE::NUMERIC/T.TOTALS)*100,2) AS PERCENTAGE_CONTRIBUTION
FROM CONTRIBUTION AS C,TOTALS AS T
Order by 3 DESC;

--TIME OF DAY--
ALTER TABLE UNIFIED_FLIGHT
ADD COLUMN TIME_OF_DAY VARCHAR;
UPDATE UNIFIED_FLIGHT
SET TIME_OF_DAY=CASE WHEN EXTRACT(HOUR FROM SCHEDULED_DEPARTURES) BETWEEN 5 AND 11 THEN 'MORNING'
            WHEN EXTRACT(HOUR FROM SCHEDULED_DEPARTURES) BETWEEN 12 AND 16 THEN 'AFTERNOON'
			WHEN EXTRACT(HOUR FROM SCHEDULED_DEPARTURES) BETWEEN 17 AND 20 THEN 'EVENING'
			ELSE 'LATE NIGHT' END;
--TIME_OF_DAY--ON TIME PERFORMANCE RATE
WITH ONTIME AS (
      SELECT TIME_OF_DAY,COUNT(*) AS ONTIMEFLIGHTS
	  FROM UNIFIED_FLIGHT
	  WHERE ARRIVALS_DELAY<15 AND ARRIVALS_TIME IS NOT NULL
	  GROUP BY 1),
	TOTALS AS( SELECT COUNT(*)AS TOTAL_FLIGHTS
	          FROM UNIFIED_FLIGHT
			  WHERE ARRIVALS_TIME IS NOT NULL)
SELECT O.TIME_OF_DAY,ROUND((O.ONTIMEFLIGHTS :: NUMERIC/T1.TOTAL_FLIGHTS)*100,2) AS ON_TIME_PERFORMANCE_RATE
FROM ONTIME AS O,TOTALS AS T1;
--TIME_OF_DAY--ARRIVAL DELAY
SELECT TIME_OF_DAY,ROUND(AVG(ARRIVALS_DELAY),2) AS AVERAGE_ARRIVAL_DELAY
                 FROM UNIFIED_FLIGHT
                  WHERE ARRIVALS_DELAY>0 AND ARRIVALS_DELAY IS NOT NULL
                 GROUP BY 1;
--TIME_OF_DAY--DEPARTURE DELAY
SELECT TIME_OF_DAY,ROUND(AVG(DEPARTURES_DELAY),2) AS AVERAGE_DEPARTURE_DELAY
                 FROM UNIFIED_FLIGHT
                 WHERE DEPARTURES_DELAY>0 AND DEPARTURES_DELAY IS NOT NULL
                 GROUP BY 1;
--TIME_OF_DAY----CANCELLATION RATE
WITH CANCELLATION AS ( SELECT TIME_OF_DAY, COUNT(CANCELLATION_REASON) AS CANCELLED FROM UNIFIED_FLIGHT
                       WHERE CANCELLATION_REASON !='NA'
					   GROUP BY 1),
	 TOTAL AS (SELECT COUNT(*) AS TOTALS FROM UNIFIED_FLIGHT)
SELECT C.TIME_OF_DAY,ROUND((C.CANCELLED::NUMERIC/T.TOTALS)*100,2) AS CANCELLATION_RATE
FROM CANCELLATION AS C,TOTAL AS T;
--TIME_OF_DAY--PERCENTAGE CONTRIBUTION OF EACH DELAY TYPE
WITH CONTRIBUTION AS(SELECT TIME_OF_DAY,CANCELLATION_REASON,COUNT(CANCELLATION_REASON) AS RATE
                     FROM UNIFIED_FLIGHT
					 WHERE CANCELLATION_REASON !='NA'
					 GROUP BY 1,2),
TOTALS AS (SELECT COUNT(CANCELLATION_REASON) AS TOTALS FROM UNIFIED_FLIGHT
           WHERE CANCELLATION_REASON!='NA')
SELECT C.TIME_OF_DAY,C.CANCELLATION_REASON,ROUND((C.RATE::NUMERIC/T.TOTALS)*100,2) AS PERCENTAGE_CONTRIBUTION
FROM CONTRIBUTION AS C,TOTALS AS T
ORDER BY 3 DESC;

